[tool.black]
target-version = ["py37"]

[tool.ruff]
target-version = "py37"
select = [
	# pycodestyle
	"E",
	"W",
	# pyflakes
	"F",
	# pyupgrade
	# Use modern Python features for the best possible develop experience.
	"UP",
	# flake8-bugbear
	# Find obvious bugs.
	"B",
	# flake8-pie
	"PIE",
	# pep8-naming
	# `Error` suffix on exception names.
	"N818",
	# flake8-simplify
	# Use 'key in dict' instead of 'key in dict.keys()'.
	"SIM118",
]
ignore = [
	# Line too long.
	# We have some places where it's just impossible to make it fit.
	"E501",
]
